# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfcvarSec < Formula
  desc "The tfcvar-sec is a tool that scanns Terraform Cloud for insecure terraform/enviroment variables."
  homepage "https://github.com/ausmartwayhashi/tfcvar-sec"
  version "0.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.5/tfcvar-sec_0.3.5_darwin_amd64.tar.gz"
      sha256 "fa33a588fbb558a3b0ec2344a2e3b53bffe743a7f83e9b3e35e3a668cf92f82e"

      define_method(:install) do
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.5/tfcvar-sec_0.3.5_darwin_arm64.tar.gz"
      sha256 "d5ea8187fa8e675532606bbe74d7a3d98dfab2f976256229977114ce7eb167c8"

      define_method(:install) do
        bin.install "tfcvar-sec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.5/tfcvar-sec_0.3.5_linux_amd64.tar.gz"
      sha256 "d694e521bcf2a84c853dc2464a4e5307006419443788a429791a1f644485ad5a"
      define_method(:install) do
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.5/tfcvar-sec_0.3.5_linux_armv6.tar.gz"
      sha256 "646bb0a1ec7bca3bbf747e5c50dcfcc0b244ad3e9bb90b20688cbea7cf3e01da"
      define_method(:install) do
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.5/tfcvar-sec_0.3.5_linux_arm64.tar.gz"
      sha256 "fc105bbeb752b0d8098dbac7cd0a526d0eaf1724dc6d49347e0fc74c75e64869"
      define_method(:install) do
        bin.install "tfcvar-sec"
      end
    end
  end

  def caveats
    <<~EOS
      Type 'tfcvar-sec scan' on your command line.
    EOS
  end

  test do
    system "#{bin}/tfcvar-sec --version"
  end
end
