# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcvar-sec" do
  name "tfcvar-sec"
  desc "The tfcvar-sec is a tool that scans Terraform Cloud for insecure terraform/environment variables."
  homepage "https://github.com/ausmartway/tfcvar-sec"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcvar-sec"

  on_macos do
    on_intel do
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v#{version}/tfcvar-sec_#{version}_darwin_amd64.tar.gz"
      sha256 "3b908dc0b008e77baaaaa26122c216e4d2a8db2cb80a504d48f41a834569973f"
    end
    on_arm do
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v#{version}/tfcvar-sec_#{version}_darwin_arm64.tar.gz"
      sha256 "9a29584a1557aef3593d382b129851bfce5a8dd6ef44f7d5326ef61139b87e51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v#{version}/tfcvar-sec_#{version}_linux_amd64.tar.gz"
      sha256 "8bd8c64dc03593488d74c79d693dd8ffde4d0a0225b6a9100f62cc747bac91cb"
    end
    on_arm do
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v#{version}/tfcvar-sec_#{version}_linux_arm64.tar.gz"
      sha256 "49221c40887e60172ccb0fd1355ce2930e608abf1200b656f2ce1bc040f588cd"
    end
  end

  caveats do
    "Type 'tfcvar-sec scan' on your command line."
  end

  # No zap stanza required
end
