# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfcvarSec < Formula
  desc "The tfcvar-sec is a tool that scanns Terraform Cloud for insecure terraform/enviroment variables."
  homepage "https://github.com/ausmartway/tfcvar-sec"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_darwin_arm64.tar.gz"
      sha256 "8ea556b6d07cc259bce49cd2e73006639291bb76478a7aa55e1f9b0742059b8b"

      def install
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_darwin_amd64.tar.gz"
      sha256 "53585a398d90f55d974682c75ef0c57795f81b0cdd3807d541d3d4ee714ebbd9"

      def install
        bin.install "tfcvar-sec"
      end
    end
    url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_darwin_all.tar.gz"
    sha256 "8615b4e30f0b596c8c2cdca1681cf9e7c78ae6d47773deebf31f637bf007224e"

    def install
      bin.install "tfcvar-sec"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_linux_armv6.tar.gz"
      sha256 "ce4eb8cb2666134c8783eb8deb0ad7d53c120f490502654c35296416ee2c0079"

      def install
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_linux_arm64.tar.gz"
      sha256 "3a9b8df5c5e1cb25e5437d6e641a19244f9bfc9398c5b71316cbd26c2f664189"

      def install
        bin.install "tfcvar-sec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.3.1/tfcvar-sec_0.3.1_linux_amd64.tar.gz"
      sha256 "ca30a5f3e969d1ca1281822d11521e2012ce50b23397f59d6f9cc72b2a642d87"

      def install
        bin.install "tfcvar-sec"
      end
    end
  end

  def caveats; <<~EOS
    Type 'tfcvar-sec scan' on your command line.
  EOS
  end

  test do
    system "#{bin}/tfcvar-sec --version"
  end
end
